-- begin FINTECH_MESSAGE
alter table FINTECH_MESSAGE add constraint FK_FINTECH_MESSAGE_ON_CUBA_USER foreign key (CUBA_USER_ID) references SEC_USER(ID)^
alter table FINTECH_MESSAGE add constraint FK_FINTECH_MESSAGE_ON_TELEGRAM_USER foreign key (TELEGRAM_USER_ID) references FINTECH_TELEGRAM_USER(ID)^
create index IDX_FINTECH_MESSAGE_ON_CUBA_USER on FINTECH_MESSAGE (CUBA_USER_ID)^
create index IDX_FINTECH_MESSAGE_ON_TELEGRAM_USER on FINTECH_MESSAGE (TELEGRAM_USER_ID)^
-- end FINTECH_MESSAGE
-- begin FINTECH_DEBIT_CARD
alter table FINTECH_DEBIT_CARD add constraint FK_FINTECH_DEBIT_CARD_ON_TELEGRAM_USER foreign key (TELEGRAM_USER_ID) references FINTECH_TELEGRAM_USER(ID)^
create index IDX_FINTECH_DEBIT_CARD_ON_TELEGRAM_USER on FINTECH_DEBIT_CARD (TELEGRAM_USER_ID)^
-- end FINTECH_DEBIT_CARD
-- begin FINTECH_CREDIT_CARD
alter table FINTECH_CREDIT_CARD add constraint FK_FINTECH_CREDIT_CARD_ON_USER_MESSAGER foreign key (USER_MESSAGER_ID) references FINTECH_TELEGRAM_USER(ID)^
create index IDX_FINTECH_CREDIT_CARD_ON_USER_MESSAGER on FINTECH_CREDIT_CARD (USER_MESSAGER_ID)^
-- end FINTECH_CREDIT_CARD
-- begin FINTECH_CREDIT
alter table FINTECH_CREDIT add constraint FK_FINTECH_CREDIT_ON_USER_MESSAGER foreign key (USER_MESSAGER_ID) references FINTECH_TELEGRAM_USER(ID)^
create index IDX_FINTECH_CREDIT_ON_USER_MESSAGER on FINTECH_CREDIT (USER_MESSAGER_ID)^
-- end FINTECH_CREDIT
