alter table FINTECH_MESSAGE add constraint FK_FINTECH_MESSAGE_ON_CUBA_USER foreign key (CUBA_USER_ID) references SEC_USER(ID);
alter table FINTECH_MESSAGE add constraint FK_FINTECH_MESSAGE_ON_TELEGRAM_USER foreign key (TELEGRAM_USER_ID) references FINTECH_TELEGRAM_USER(ID);
create index IDX_FINTECH_MESSAGE_ON_CUBA_USER on FINTECH_MESSAGE (CUBA_USER_ID);
create index IDX_FINTECH_MESSAGE_ON_TELEGRAM_USER on FINTECH_MESSAGE (TELEGRAM_USER_ID);
